# - Tomato: hsl(4, 100%, 67%)
# - Dark Slate Grey: hsl(234, 29%, 20%)
# - Charcoal Grey: hsl(235, 18%, 26%)
# - Grey: hsl(231, 7%, 60%)
# - White: hsl(0, 0%, 100%)
[colors]
type = "color"
base = "hsl(235, 18%, 26%)"
secondary = "hsl(234, 29%, 20%)"
accent = "hsl(0, 0%, 100%)"
base-light = "hsl(231, 7%, 60%)"
primary = "hsl(4, 100%, 67%)"
