[fontWeight]
type = "fontWeight"
regular = "400"
medium = "700"

[lineHeight]
type = "lineHeight"
flat = 1
fine = 1.15
standart = 1.5
loose = 1.7

[fontFamily]
type = "font"
base = "Roboto, Arial, sans-serif"
